//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int ID_Admission { get; set; }
        public bool Chirurgie_Programmee { get; set; }
        public System.DateTime Date_Admission { get; set; }
        public Nullable<System.DateTime> Date_Chirurgie { get; set; }
        public Nullable<System.DateTime> Date_Du_Conge { get; set; }
        public Nullable<bool> Televiseur { get; set; }
        public Nullable<bool> Telephone { get; set; }
        public string NSS { get; set; }
        public Nullable<int> Numero_Lit { get; set; }
        public Nullable<int> ID_Medecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
